# Generated by Django 3.2.9 on 2021-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211224_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
