# Generated by Django 3.2.9 on 2021-12-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211224_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('title', 'slug')},
        ),
    ]
