# Generated by Django 3.2.9 on 2021-12-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_work_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='label',
            field=models.CharField(choices=[('Speaking', 'Speaking'), ('Project', 'Project')], max_length=200, null=True),
        ),
    ]
