# Generated by Django 3.2.9 on 2021-12-28 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211227_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='overview',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
